In [1]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)
print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
placement_df = pd.read_csv(r"C:\Users\rohit\Documents\CareerInsight AI Student Placement Prediction & Analytics Platform\data\raw\Indian_Student_Placement_Dataset_2025.csv")

In [3]:
salary_df = pd.read_csv(r"C:\Users\rohit\Documents\CareerInsight AI Student Placement Prediction & Analytics Platform\data\raw\ai_job_salary_dataset_10k.csv")

In [4]:
skill_df = pd.read_csv(r"C:\Users\rohit\Documents\CareerInsight AI Student Placement Prediction & Analytics Platform\data\raw\DMA DATASET.csv")

In [5]:
print("Placement Dataset:", placement_df.shape)
print("Salary Dataset:", salary_df.shape)
print("Skill Dataset:", skill_df.shape)

Placement Dataset: (12000, 16)
Salary Dataset: (10000, 7)
Skill Dataset: (500, 15)

In [6]:
placement_df.head()
salary_df.head()
skill_df.head()

,Name,email_id,Year,Current Course,Technical Skills,Programming Languages,Rating,Soft Skills,Rating.1,Projects,Career Interest,Challenges,Support required,Unnamed: 13,Method
0,Iorgo Hakonsen,ihakonsen0@instagram.com,2nd,MBA,"Cybersecurity, Blockchain","Python, R, C#",2,"Communication, Adaptability, Problem-Solving",1,Yes,Data Scientist,Interview anxiety,Mentorship programs,NaN,College curriculum
1,Emmery Duffyn,eduffyn1@dailymotion.com,Final,BBA,"SQL, Machine Learning","R, Go",3,"Leadership, Communication, Problem-Solving",4,No,AI Engineer,No networking opportunities,Technical skill training,NaN,College curriculum
2,Susanetta Wards,swards2@digg.com,2nd,B.Sc Data Science,"Cybersecurity, Java",JavaScript,4,"Leadership, Time Management, Problem-Solving",1,No,Data Scientist,Interview anxiety,Technical skill training,NaN,Self-study
3,Amanda Gussin,agussin3@webs.com,2nd,M.Tech AI,"Blockchain, Python, SQL","Python, C#",3,"Adaptability, Teamwork, Leadership",4,No,Cybersecurity Expert,Limited guidance,Resume workshops,NaN,College curriculum
4,Carlina Beaven,cbeaven4@timesonline.co.uk,1st,B.Tech IT,"Blockchain, Machine Learning, Python","Java, Go",4,"Teamwork, Adaptability, Problem-Solving",3,Yes,Cybersecurity Expert,No networking opportunities,Internship opportunities,NaN,Online

In [7]:
#inspect the dataset 
print("=" * 60)
print("PLACEMENT DATASET INFORMATION")
print("=" * 60)

print("\nShape:")
print(placement_df.shape)

print("\nColumns:")
print(placement_df.columns.tolist())

print("\nDataset Info:")
placement_df.info()

print("\nMissing Values:")
print(placement_df.isnull().sum())

print("\nDuplicate Rows:")
print(placement_df.duplicated().sum())

print("\nNumerical Summary:")
display(placement_df.describe())

print("\nCategorical Summary:")
display(placement_df.describe(include='object'))

============================================================
PLACEMENT DATASET INFORMATION
============================================================

Shape:
(12000, 16)

Columns:
['student_id', 'gender', 'age', 'degree', 'branch', 'cgpa', 'backlogs', 'internships', 'certifications', 'coding_skills', 'communication_skills', 'aptitude_score', 'projects', 'placed', 'company_type', 'package_lpa']

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            12000 non-null  int64
 1   gender                12000 non-null  object
 2   age                   12000 non-null  int64
 3   degree                12000 non-null  object
 4   branch                12000 non-null  object
 5   cgpa                  12000 non-null  float64
 6   backlogs              12000 non-null  int64
 7   internships           12000 non-null  int64
 8   certifications        12000 non-null  int64
 9   coding_skills         12000 non-null  int64
 10  communication_skills  12000 non-null  int64
 11  aptitude_score        12000 non-null  int64
 12  projects              12000 non-null  int64
 13  placed                12000 non-null  int64
 14  company_type          3652 non-null   object
 15  package_lpa           12000 non-null  float64
dtypes: float64(2), int64(10), object(4)
memory usage: 1.5+ MB

Missing Values:
student_id                 0
gender                     0
age                        0
degree                     0
branch                     0
cgpa                       0
backlogs                   0
internships                0
certifications             0
coding_skills              0
communication_skills       0
aptitude_score             0
projects                   0
placed                     0
company_type            8348
package_lpa                0
dtype: int64

Duplicate Rows:
0

Numerical Summary:

,student_id,age,cgpa,backlogs,internships,certifications,coding_skills,communication_skills,aptitude_score,projects,placed,package_lpa
count,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,6000.50000,21.988333,7.645308,1.491583,1.501167,2.509000,5.495333,5.500583,69.327833,2.504750,0.304333,2.741692
std,3464.24595,1.422158,1.243433,1.118347,1.123582,1.709092,2.889724,2.888459,17.338207,1.699133,0.460144,4.568126
min,1.00000,20.000000,5.500000,0.000000,0.000000,0.000000,1.000000,1.000000,40.000000,0.000000,0.000000,0.000000
25%,3000.75000,21.000000,6.560000,0.000000,0.000000,1.000000,3.000000,3.000000,54.000000,1.000000,0.000000,0.000000
50%,6000.50000,22.000000,7.645000,1.000000,1.000000,3.000000,5.000000,6.000000,69.000000,3.000000,0.000000,0.000000
75%,9000.25000,23.000000,8.720000,2.000000,3.000000,4.000000,8.000000,8.000000,84.000000,4.000000,1.000000,5.170000
max,12000.00000,24.000000,9.800000,3.000000,3.000000,5.000000,10.000000,10.000000,99.000000,5.000000,1.000000,15.000000

Categorical Summary:

       gender degree      branch company_type
count   12000  12000       12000         3652
unique      2      4           6            3
top      Male    BCA  Mechanical      Product
freq     6008   3071        2107         1252

In [8]:
#Repeat for the Salary Dataset

print("=" * 60)
print("SALARY DATASET INFORMATION")
print("=" * 60)

print(salary_df.columns.tolist())
salary_df.info()
salary_df.isnull().sum()
salary_df.duplicated().sum()

display(salary_df.describe())
display(salary_df.describe(include='object'))

============================================================
SALARY DATASET INFORMATION
============================================================
['id', 'job_role', 'country', 'experience_level', 'salary_usd', 'skills', 'company_type']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                10000 non-null  int64
 1   job_role          10000 non-null  object
 2   country           10000 non-null  object
 3   experience_level  10000 non-null  object
 4   salary_usd        10000 non-null  int64
 5   skills            10000 non-null  object
 6   company_type      10000 non-null  object
dtypes: int64(2), object(5)
memory usage: 547.0+ KB

                id     salary_usd
count  10000.00000   10000.000000
mean    5000.50000   95210.201300
std     2886.89568   58450.013652
min        1.00000    8023.000000
25%     2500.75000   45051.000000
50%     5000.50000   81579.000000
75%     7500.25000  140388.250000
max    10000.00000  239379.000000

,job_role,country,experience_level,skills,company_type
count,10000,10000,10000,10000,10000
unique,8,6,4,720,3
top,Computer Vision Engineer,Germany,Mid,"SQL, MLOps, Python",Mid-size
freq,1289,1729,2573,27,3365

In [9]:
#Repeat for the Skill Dataset
print("=" * 60)
print("SKILL DATASET INFORMATION")
print("=" * 60)

print(skill_df.columns.tolist())
skill_df.info()
skill_df.isnull().sum()
skill_df.duplicated().sum()

display(skill_df.describe())
display(skill_df.describe(include='object'))

============================================================
SKILL DATASET INFORMATION
============================================================
['Name', 'email_id', 'Year ', 'Current Course', 'Technical Skills', '     Programming Languages', 'Rating', 'Soft Skills', 'Rating.1', ' Projects', 'Career Interest', 'Challenges ', 'Support required', 'Unnamed: 13', ' Method']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Name                        500 non-null    object
 1   email_id                    500 non-null    object
 2   Year                        500 non-null    object
 3   Current Course              500 non-null    object
 4   Technical Skills            500 non-null    object
 5        Programming Languages  500 non-null    object
 6   Rating                      500 non-null    int64
 7   Soft Skills                 500 non-null    object
 8   Rating.1                    500 non-null    int64
 9    Projects                   500 non-null    object
 10  Career Interest             500 non-null    object
 11  Challenges                  500 non-null    object
 12  Support required            500 non-null    object
 13  Unnamed: 13                 0 non-null      float64
 14   Method                     500 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 58.7+ KB

           Rating    Rating.1  Unnamed: 13
count  500.000000  500.000000          0.0
mean     2.952000    2.956000          NaN
std      1.404864    1.440213          NaN
min      1.000000    1.000000          NaN
25%      2.000000    2.000000          NaN
50%      3.000000    3.000000          NaN
75%      4.000000    4.000000          NaN
max      5.000000    5.000000          NaN

,Name,email_id,Year,Current Course,Technical Skills,Programming Languages,Soft Skills,Projects,Career Interest,Challenges,Support required,Method
count,500,500,500,500,500,500,500,500,500,500,500,500
unique,500,500,9,6,336,161,135,2,6,5,4,4
top,Kiel Meysham,kmeyshamdv@purevolume.com,Final Year,MBA,"Data Analysis, Cybersecurity",R,"Problem-Solving, Teamwork",No,Cloud Architect,No networking opportunities,Resume workshops,College curriculum
freq,1,1,129,93,9,34,13,254,98,112,143,139

In [10]:
placement_df.columns.tolist()

['student_id',
 'gender',
 'age',
 'degree',
 'branch',
 'cgpa',
 'backlogs',
 'internships',
 'certifications',
 'coding_skills',
 'communication_skills',
 'aptitude_score',
 'projects',
 'placed',
 'company_type',
 'package_lpa']

In [11]:
salary_df.columns.tolist()

['id',
 'job_role',
 'country',
 'experience_level',
 'salary_usd',
 'skills',
 'company_type']

In [12]:
skill_df.columns.tolist()

['Name',
 'email_id',
 'Year ',
 'Current Course',
 'Technical Skills',
 '     Programming Languages',
 'Rating',
 'Soft Skills',
 'Rating.1',
 ' Projects',
 'Career Interest',
 'Challenges ',
 'Support required',
 'Unnamed: 13',
 ' Method']